AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'spec/**/*.rb'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Style/GuardClause:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
  
