require: rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

Layout/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/GuardClause:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/**/*.rb'
