version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.0
        environment:
          RAILS_ENV: test
caches:
  - &bundle_cache v3-repo-{{ checksum "Gemfile.lock" }}

commands:
  update_bundler:
    steps:
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop

  run_specs:
    steps: 
      - run: 
          name: run specs
          command: bundle exec rspec --format progress
      - store_test_results:
          path: /tmp/test-results 

jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
