version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.0


cashes:
  - &bundle_caches_v1 v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  update_bundler:
    steps:
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubucop
          command: bundle exec rubocop
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec --format progress
      - store_artifacts:
          path: /tmp/test-results

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
