require 'yaml'

require 'i18n'
require_relative 'config/i18n_config'

require_relative 'errors/not_enough_money_error'
require_relative 'errors/too_small_amount_error'
require_relative 'entities/base_card'
require_relative 'entities/usual_card'
require_relative 'entities/virtual_card'
require_relative 'entities/capitalist_card'
require_relative 'modules/storage'
require_relative 'modules/helper'
require_relative 'entities/account_validation'
require_relative 'entities/account'
require_relative 'entities/account_manager'
require_relative 'entities/card'
require_relative 'entities/transaction'
require_relative 'entities/console'

require_relative 'states/base_state'
require_relative 'states/state'
require_relative 'states/create_account'
require_relative 'states/account_load'
require_relative 'states/destroy_account'
require_relative 'states/menu_account'
require_relative 'states/show_cards'
require_relative 'states/create_card'
require_relative 'states/destroy_card'
require_relative 'states/put_money'
require_relative 'states/money_withdraw'
require_relative 'states/send_money'
